### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by ankitsmt211** [Together-Java/TJ-Bot#1157]
**Describe the bug**

Something off with the routine, 
[org.togetherjava.tjbot.features.help.MarkHelpThreadCloseInDBRoutine](https://github.com/Together-Java/TJ-Bot/blob/master/application/src/main/java/org/togetherjava/tjbot/features/help/MarkHelpThreadCloseInDBRoutine.java)
WARN
unable to mark thread as close with id :1256940271854157855
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.channel.concrete.ThreadChannel.getIdLong()" because "threadChannel" is null
at org.togetherjava.tjbot.features.help.HelpThreadLifecycleListener.handleArchiveStatus(HelpThreadLifecycleListener.java:86)
at org.togetherjava.tjbot.features.help.MarkHelpThreadCloseInDBRoutine.lambda$updateTicketStatus$1(MarkHelpThreadCloseInDBRoutine.java:66)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.togetherjava.tjbot.features.help.MarkHelpThreadCloseInDBRoutine.updateTicketStatus(MarkHelpThreadCloseInDBRoutine.java:63)
at org.togetherjava.tjbot.features.help.MarkHelpThreadCloseInDBRoutine.runRoutine(MarkHelpThreadCloseInDBRoutine.java:49)
at org.togetherjava.tjbot.features.system.BotCore.lambda$scheduleRoutines$7(BotCore.java:199)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/jav...

**Expected behavior**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by ankitsmt211** [comment]
@Zabuzard  a bit of context, some of the threads are left as active in help_thread database table. This routine is meant to run every 24 Hrs and find the ones that are still marked as active even after 3 days since creation for whatever reason. 

part of routine, finds that record which is still marked as active and fetches that thread_channel by ID since its possible that channel may not exist at that point of time it executes further logic in try-catch where catch simply logs that channel is not present. 

Im planning to do certain changes, would love some thoughts on this
* if a channel no longer exists at discord level, should it still be kept in our help_thread stats?
* if a channel no longer exists, instead of just logging i think except block should also mark it archived in help_thread table
