### ISSUE TITLE
/free fails if status-message is deleted hot

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#323]
# Description

When using the `/free` command to mark a channel free, after the bots status-message in `#open_channel_info` has been deleted (for example by a moderator) while the bot is running (i.e. it confirmed that the message exists during startup but its deleted afterwards), the command fails with an exception:

```java
tjbot-develop_1  | 13:28:23.236 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.api.JDA - One of the EventListeners had an uncaught exception
tjbot-develop_1  | net.dv8tion.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message
tjbot-develop_1  |      at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227) ~[JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633) ~[JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at java.util.Optional.map(Optional.java:260) ~[?:?]
tjbot-develop_1  |      at org.togetherjava.tjbot.commands.free.FreeCommand.getStatusMessageIn(FreeCommand.java:314) ~[classes/:?]
tjbot-develop_1  |      at org.togetherjava.tjbot.commands.free.FreeCommand.displayStatus(FreeCommand.java:207) ~[classes/:?]
tjbot-develop_1  |      at org.togetherjava.tjbot.commands.free.FreeCommand.onEvent(FreeCommand.java:303) ~[classes/:?]
tjbot-develop_1  |      at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991) [JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) [nv-websocket-client-2.14.jar:?]
tjbot-develop_1  |      at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) [nv-websocket-client-2.14.jar:?]
tjbot-develop_1  |      at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) [nv-websocket-client-2.14.jar:?]
tjbot-develop_1  |      at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) [nv-websocket-client-2.14.jar:?]
tjbot-develop_1  |      at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [nv-websocket-client-2.14.jar:?]
tjbot-develop_1  |      at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [nv-websocket-client-2.14.jar:?]
tjbot-develop_1  |      at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [nv-websocket-client-2.14.jar:?]
tjbot-develop_1  | Caused by: net.dv8tion.jda.api.exceptions.ContextException
tjbot-develop_1  |      at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71) ~[JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36) ~[JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) ~[JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) ~[JDA-4.4.0_351.jar:4.4.0_351]
tjbot-develop_1  |      ... 22 more
```

# Steps to reproduce

1. Start the bot
2. Delete the status message in `#open_channel_info`
3. Use `/free` in a help channel, it fails

# Workaround

Temporary, one can work around this issue by simply **restarting** the bot.

**Comment by Zabuzard** [comment]
@borgrel for visibility

**Comment by Tais993** [comment]
Suggestion, create a method that wraps around retrieving/sending a new message.
If you send a new message, it returns a RestAction<Message>.
If you retrieve a message, it returns a RestAction<Message>

So the code following it doesn't have to change.
