### ISSUE TITLE
Help-Thread created handle fails if too fast

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#723]
Sometimes when people post new help threads, our actions that are executed upon creation (explanation message, helper ping, ...) run too fast and are technically executed after Discord created the thread, but before Discord posted the initial message by the user. When that happens, we get an exception and the whole action-chain fails:
```java
ERROR net.dv8tion.jda.api.requests.RestAction - RestAction queue returned failure: [ErrorResponseException] 40058: Cannot message this thread  until after the post author has sent an initial message.
net.dv8tion.jda.api.exceptions.ContextException: null
       at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.requests.restaction.operator.RestActionOperator.contextWrap(RestActionOperator.java:123) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.requests.restaction.operator.FlatMapRestAction.queue(FlatMapRestAction.java:50) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at org.togetherjava.tjbot.commands.help.HelpThreadCreatedListener.handleHelpThreadCreated(HelpThreadCreatedListener.java:72) ~[classes/:?]
       at org.togetherjava.tjbot.commands.help.HelpThreadCreatedListener.onChannelCreate(HelpThreadCreatedListener.java:57) ~[classes/:?]
       at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:403) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:173) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.handle.ThreadCreateHandler.handleInternally(ThreadCreateHandler.java:42) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:961) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:847) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:825) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1000) ~[JDA-5.0.0-alpha.20.jar:5.0.0-alpha.20]
       at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar:?]
       at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar:?]
       at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar:?]
       at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar:?]
       at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar:?]
       at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar:?]
       at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar:?]
```

This happens about 1-2 times per day and has to be fixed. It is probably not easy to fix this properly by actually waiting for the first message to appear. Hence, it would also be okay to just delay the action-chain by, lets say 5 seconds. That should mitigate the issue in practice. The class to do the changes will likely be `HelpThreadCreatedListener`.

(Dont use `Thread.sleep` or other blocking mechanisms, use a `ScheduledExecutorService` with `schedule(task, 5, TimeUnit.SECONDS)` instead)

**Comment by Zabuzard** [comment]
Gonna take this due to the urge.
